### ISSUE TITLE
Confetti flickering

### ISSUE THREAD

**Issue by vojtatranta** [alampros/react-confetti#71] opened 2019-10-07 11:52 UTC
Hi!
Thank you for your great package! We have been using it for quite some time and it worked well until recently.

Unfortunately, I can't say when it broke but if you check out the video below confetti behaves strangely.

Any clue why is that?

Video: https://imgur.com/6QvV0ie

Thanks!

**Comment by alampros** [comment] 2019-10-18 17:48
Thanks for submitting this video - I haven't been able to reproduce this, so I haven't actually seen this bug in action.

I'm going to close this as a duplicate of #56 so I can track it on one issue.

Could you please provide some environment information to help narrow it down (OS, browser version, etc) over on #56 ?

Thank you!

**Closed by alampros** 2019-10-18 17:48 UTC
Labels: duplicate
